CREATE DATABASE DB_BIBLIOTECHNOLOGY
USE DB_BIBLIOTECHNOLOGY

CREATE TABLE TB_BIBLIOTECARIO(
USUARIO_BLI VARCHAR(25) PRIMARY KEY,
SENHA_BLI VARCHAR(30),
NOME_BLI VARCHAR(150),
EMAIL_BLI VARCHAR(200),
SEXO_BLI BIT,
ATIVO_BLI BIT
)

CREATE TABLE TB_LOCATARIO(
COD_LOC INT PRIMARY KEY IDENTITY(1,1),
TIPO_LOC INT,
RM_LOC INT,
CPF_LOC VARCHAR(14),
NOME_LOC VARCHAR(150),
SEXO_LOC BIT,
TURMA_LOC VARCHAR(10),
TEL_LOC VARCHAR (13),
CEL_LOC VARCHAR (14),
END_LOC VARCHAR(255),
NUMERO_LOC INT,
COMPLEMENTO_LOC VARCHAR(20),
BAIRRO_LOC VARCHAR(50),
CIDADE_LOC VARCHAR (50),
CEP_LOC VARCHAR(8),
OBS_LOC VARCHAR (255),
ATIVO_LOC BIT
)

CREATE TABLE TB_GENERO(
GENERO VARCHAR (20) PRIMARY KEY 
)

CREATE TABLE TB_EDITORA(
COD_EDIT INT PRIMARY KEY IDENTITY(1,1),
NOME_EDIT VARCHAR(100),
TEL_EDIT VARCHAR (13),
EMAIL_EDIT VARCHAR (255),
SITE_EDIT VARCHAR (255),
END_EDIT VARCHAR(255),
NUMERO_EDIT INT,
COMPLEMENTO_EDIT VARCHAR(20),
BAIRRO_EDIT VARCHAR(50),
CIDADE_EDIT VARCHAR (50),
CEP_EDIT VARCHAR(8)
)

CREATE TABLE TB_TIPO_MATERIAL(
TIPO_MATERIAL VARCHAR(20) PRIMARY KEY
)

CREATE TABLE TB_LIVRO(
COD_LIVRO INT PRIMARY KEY IDENTITY(1,1),
TITULO_LIVRO VARCHAR(100),
AUTOR_LIVRO VARCHAR(150),
EDICAO_LIVRO VARCHAR(20),
ANO_LANCAMENTO VARCHAR(4),
GENERO VARCHAR(20) REFERENCES TB_GENERO(GENERO),
COD_EDIT INT REFERENCES TB_EDITORA (COD_EDIT),
LUGAR_LIVRO VARCHAR(50),
ATIVO_LIVRO BIT,
ALUGA_LIVRO BIT,
ALUGADO_LIVRO BIT,
TIPO_MATERIAL VARCHAR(20) REFERENCES TB_TIPO_MATERIAL(TIPO_MATERIAL),
OBS_LIVRO VARCHAR(200)
)


CREATE TABLE TB_MOVIMENTACAO(
COD_MOVIMENTACAO INT PRIMARY KEY IDENTITY(1,1),
TIPO_MATERIAL VARCHAR(10),
MOVIMENTACAO VARCHAR(10),
DATA_MOVIMENTACAO DATETIME
)

CREATE TABLE TB_LOCACAO(
COD_LOCACAO INT PRIMARY KEY IDENTITY(1,1),
COD_LOC INT REFERENCES TB_LOCATARIO(COD_LOC),
COD_LIVRO INT REFERENCES TB_LIVRO(COD_LIVRO),
DATA_LOCACAO DATE,
DATA_DEVOLUCAO DATE,
DEVOLUCAO DATE,
)
/*
CREATE TABLE TB_RESERVA(
COD_RESERVA INT PRIMARY KEY IDENTITY(1,1),
COD_LOC INT REFERENCES TB_LOCATARIO(COD_LOC),
COD_LIVRO INT REFERENCES TB_LIVRO(COD_LIVRO)
)*/

CREATE TABLE TB_CONFIGURACAO(
COD_CONFIG INT PRIMARY KEY IDENTITY(1,1),
TEMPO_LOCACAO_ALUNO INT,
TEMPO_LOCACAO_FUNCIONARIO INT,
TEMPO_LOCACAO_SERVIDOR INT,
TEMPO_LOCACAO_PUBLICO INT,
QUANTIDADE_LIVROS_ALUNO INT,
QUANTIDADE_LIVROS_FUNCIONARIO INT,
QUANTIDADE_LIVROS_SERVIDOR INT,
QUANTIDADE_LIVROS_PUBLICO INT,

)

INSERT INTO TB_BIBLIOTECARIO VALUES ('admin','admin','admin','',1,1)

INSERT INTO TB_CONFIGURACAO VALUES (15,20,15,15,2,3,2,2)


SELECT * FROM TB_CONFIGURACAO WHERE COD_CONFIG = 1

SELECT TB_LIVROS.TITULO_LIVRO,TB_LOCACAO.DATA_DEVOLCAO,TB_LOCATARIO.NOME_LOC
FROM TB_LIVROS, TB_LOCATARIO, TB_LOCACAO
WHERE TB_LOCATARIO.COD_LOC = TB_LOCACAO.COD_LOC AND
		TB_LIVROS.COD_LIVRO = TB_LOCACAO.COD_LIVRO AND
		TB_LOCACAO.DEVOLUCAO IS NULL 

SELECT MAX(COD_LIVRO) FROM TB_LIVRO

SELECT * FROM TB_LOCACAO WHERE COD_LOC = 1 AND DEVOLUCAO IS NULL

UPDATE TB_LIVRO SET ALUGADO_LIVRO = 'FALSE' WHERE COD_LIVRO = 5

SELECT DISTINCT COD_LOC FROM TB_LOCACAO WHERE DATA_DEVOLUCAO <= '30-05-2016' AND DEVOLUCAO IS NULL

SELECT TB_LIVRO.COD_LIVRO,TB_LIVRO.TITULO_LIVRO,TB_LOCATARIO.NOME_LOC,TB_LOCATARIO.TURMA_LOC,TB_LOCATARIO.TEL_LOC,TB_LOCACAO.DATA_DEVOLUCAO
FROM TB_LIVRO,TB_LOCACAO,TB_LOCATARIO
WHERE TB_LIVRO.COD_LIVRO = TB_LOCACAO.COD_LIVRO AND TB_LOCACAO.COD_LOC = TB_LOCATARIO.COD_LOC AND TB_LOCACAO.DEVOLUCAO IS NULL AND DATA_DEVOLUCAO = '15-05-2016'

SELECT TB_LIVRO.COD_LIVRO,TB_LIVRO.TITULO_LIVRO,TB_LOCATARIO.NOME_LOC,TB_LOCATARIO.TURMA_LOC,TB_LOCATARIO.TEL_LOC,TB_LOCACAO.DATA_DEVOLUCAO
FROM TB_LIVRO,TB_LOCACAO,TB_LOCATARIO
WHERE TB_LIVRO.COD_LIVRO = TB_LOCACAO.COD_LIVRO AND TB_LOCACAO.COD_LOC = TB_LOCATARIO.COD_LOC AND TB_LOCACAO.DEVOLUCAO IS NULL AND DATA_DEVOLUCAO < '01-07-2016'

SELECT LI.COD_LIVRO AS 'Código',LI.TITULO_LIVRO AS 'Título', LOC.NOME_LOC AS 'Nome',LOC.TURMA_LOC As 'Turma',LOC.TEL_LOC AS 'Tel', LOCACAO.DATA_DEVOLUCAO AS 'Data de devolução' FROM TB_LIVRO AS LI INNER JOIN TB_LOCACAO AS LOCACAO ON LI.COD_LIVRO = LOCACAO.COD_LIVRO INNER JOIN TB_LOCATARIO AS LOC ON LOCACAO.COD_LOC = LOC.COD_LOC WHERE  LOCACAO.DEVOLUCAO IS NULL AND LOCACAO.DATA_DEVOLUCAO = '15-05-2016'

SELECT LI.COD_LIVRO AS 'Código',LI.TITULO_LIVRO AS 'Título', LOC.NOME_LOC AS 'Nome',LOC.TURMA_LOC As 'Turma',LOC.TEL_LOC AS 'Tel', LOCACAO.DATA_DEVOLUCAO AS 'Data de devolução' FROM TB_LIVRO AS LI INNER JOIN TB_LOCACAO AS LOCACAO ON LI.COD_LIVRO = LOCACAO.COD_LIVRO INNER JOIN TB_LOCATARIO AS LOC ON LOCACAO.COD_LOC = LOC.COD_LOC WHERE  LOCACAO.DEVOLUCAO IS NULL AND LOCACAO.DATA_DEVOLUCAO < '15-05-2016'

 SELECT MOVIMENTACAO, TIPO_MATERIAL , COUNT(MOVIMENTACAO) AS 'Quantidade' FROM TB_MOVIMENTACAO WHERE DATA_MOVIMENTACAO > '20106630 22:47:31' AND DATA_MOVIMENTACAO <  '20160701 22:47:31'  GROUP BY MOVIMENTACAO ,TIPO_MATERIAL  
 SELECT * FROM TB_MOVIMENTACAO

 SELECT * FROM TB_LOCATARIO WHERE COD_LOC='1003'

 SELECT * FROM TB_BIBLIOTECARIO WHERE ATIVO_BLI='TRUE'