INSERT INTO TB_EDITORA (NOME_EDIT) VALUES ('EDITORA')
INSERT INTO TB_GENERO VALUES ('GENERO')
INSERT INTO TB_TIPO_MATERIAL VALUES('LIVRO')
INSERT INTO TB_LIVRO (TITULO_LIVRO,AUTOR_LIVRO,GENERO,COD_EDIT,TIPO) VALUES ('LIVRO1','AUTOR1','GENERO','1','LIVRO')

INSERT INTO TB_LOCATARIO (NOME_LOC) VALUES ('JOÃO')
