CREATE DATABASE DB_BIBLIOTECHNOLOGY
USE DB_BIBLIOTECHNOLOGY

CREATE TABLE TB_BIBLIOTECARIO(
USUARIO_BLI VARCHAR(25) PRIMARY KEY,
SENHA_BLI VARCHAR(30),
NOME_BLI VARCHAR(150),
EMAIL_BLI VARCHAR(200),
SEXO BIT,
ATIVO_BLI BIT
)

CREATE TABLE TB_LOCATARIO(
COD_LOC INT PRIMARY KEY IDENTITY,
TIPO_LOC INT,
RM_LOC INT,
CPF VARCHAR(14),
NOME_LOC VARCHAR(150),
SEXO_LOC BIT,
TURMA_LOC VARCHAR(10),
TEL_LOC VARCHAR (13),
CEL_LOC VARCHAR (14),
END_LOC VARCHAR(255),
NUMERO_LOC INT,
COMPLEMENTO_LOC VARCHAR(20),
BAIRRO_LOC VARCHAR(50),
CIDADE_LOC VARCHAR (50),
CEP_LOC INT,
OBS_LOC VARCHAR (255),
ATIVO_LOC BIT
)

CREATE TABLE TB_GENERO(
GENERO VARCHAR (20) PRIMARY KEY 
)

CREATE TABLE TB_EDITORA(
COD_EDIT INT PRIMARY KEY IDENTITY(1,1),
NOME_EDIT VARCHAR(100),
TEL_EDIT VARCHAR (13),
EMAIL_EDIT VARCHAR (255),
SITE_EDIT VARCHAR (255),
END_EDIT VARCHAR(255),
NUMERO_EDIT INT,
COMPLEMENTO_EDIT VARCHAR(20),
BAIRRO_EDIT VARCHAR(50),
CIDADE_EDIT VARCHAR (50),
CEP_EDIT INT
)

CREATE TABLE TB_LIVRO(
COD_LIVRO INT PRIMARY KEY IDENTITY(1,1),
TITULO_LIVRO VARCHAR(100),
AUTOR_LIVRO VARCHAR(150),
EDICAO_LIVRO VARCHAR(20),
ANO_LANÇAMENTO VARCHAR(4),
GENERO VARCHAR(20) REFERENCES TB_GENERO(GENERO),
COD_EDIT INT REFERENCES TB_EDITORA (COD_EDIT),
LUGAR_LIVRO VARCHAR(50),
ATIVO_LIVRO BIT,
OBS_LIVRO VARCHAR(200)
)

CREATE TABLE TB_LOCACAO(
COD_LOCACAO INT PRIMARY KEY IDENTITY(1,1),
COD_LOC INT REFERENCES TB_LOCATARIO(COD_LOC),
COD_LIVRO INT REFERENCES TB_LIVRO(COD_LIVRO),
DATA_LOCACAO DATE,
DATA_DEVOLCAO DATE,
DEVOLUCAO DATE,
)

CREATE TABLE TB_CONFIGURACAO(
COD_CONFIG INT PRIMARY KEY IDENTITY(1,1),
MAX_LIVROS_ALUGADOS INT,
TEMPO_LOCACAO_ALUNO INT,
TEMPO_LOCACAO_FUNCIOARIO INT,
TEMPO_LOCACAO_PUBLICO INT,
QUANTIDADE_LIVROS_ALUNO INT,
QUANTIDADE_LIVROS_FUNCIONARIOS INT,
QUANTIDADE_LIVROS_PUBLICO INT
)



SELECT TB_LIVROS.TITULO_LIVRO,TB_LOCACAO.DATA_DEVOLCAO,TB_LOCATARIO.NOME_LOC
FROM TB_LIVROS, TB_LOCATARIO, TB_LOCACAO
WHERE TB_LOCATARIO.COD_LOC = TB_LOCACAO.COD_LOC AND
		TB_LIVROS.COD_LIVRO = TB_LOCACAO.COD_LIVRO AND
		TB_LOCACAO.DEVOLUCAO IS NULL 