CREATE TABLE TB_BIBLIOTECARIO(
USUARIO_BLI VARCHAR(25) PRIMARY KEY,
SENHA_BLI VARCHAR(30),
NOME_BLI VARCHAR(150),
EMAIL_BLI VARCHAR(200),
SEXO BIT,
ATIVO_BLI BIT
)

CREATE TABLE TB_ALUNO(
COD_ALU INT PRIMARY KEY,
NOME_ALU VARCHAR(150),
SEXO BIT,
TURMA_ALU VARCHAR(10),
TEL_ALU VARCHAR (13),
CEL_ALU VARCHAR (14),
END_ALU VARCHAR(255),
NUMERO_ALU INT,
COMPLEMENTO_ALU VARCHAR(20),
BAIRRO_ALU VARCHAR(50),
CIDADE_ALU VARCHAR (50),
CEP_ALU INT,
OBS VARCHAR (255),
ATIVO BIT
)

CREATE TABLE TB_FUNCIONARIO(
COD_FUN INT PRIMARY KEY,
NOME_FUN VARCHAR(150),
SEXO BIT,
TEL_FUN VARCHAR (13),
CEL_FUN VARCHAR (14),
END_FUN VARCHAR(255),
NUMERO_FUN INT,
COMPLEMENTO_FUN VARCHAR(20),
BAIRRO_FUN VARCHAR(50),
CIDADE_FUN VARCHAR (50),
CEP_FUN INT,
OBS VARCHAR(255),
ATIVO BIT
)


CREATE TABLE TB_GENERO(
GENERO VARCHAR (20) PRIMARY KEY 
)

CREATE TABLE TB_EDITORA(
COD_EDIT INT PRIMARY KEY IDENTITY(1,1),
NOME_EDIT VARCHAR(100),
TEL_EDIT VARCHAR (13),
EMAIL_EDIT VARCHAR (255),
SITE_EDIT VARCHAR (255),
END_EDIT VARCHAR(255),
NUMERO_EDIT INT,
COMPLEMENTO_EDIT VARCHAR(20),
BAIRRO_EDIT VARCHAR(50),
CIDADE_EDIT VARCHAR (50),
CEP_EDIT INT
)

CREATE TABLE TB_LIVROS(
COD_LIVRO INT PRIMARY KEY IDENTITY(1,1),
TITULO_LIVRO VARCHAR(100),
AUTOR_LIVRO VARCHAR(150),
EDICAO_LIVRO VARCHAR(20),
ANO_LANÇAMENTO VARCHAR(4),
GENERO VARCHAR(20) REFERENCES TB_GENERO(GENERO),
COD_EDIT INT REFERENCES TB_EDITORA (COD_EDIT),
LUGAR_LIVRO VARCHAR(50),
ATIVO_LIVRO BIT,
OBS_LIVRO VARCHAR(200)
)

CREATE TABLE TB_LOCACAO(
COD_LOCACAO INT PRIMARY KEY IDENTITY(1,1),
COD_ALU INT REFERENCES TB_ALUNO(COD_ALU),
COD_LIVRO INT REFERENCES TB_LIVROS(COD_LIVRO),
DATA_LOCACAO DATE,
DATA_DEVOLCAO DATE,
DEVOLUCAO DATE,
)

CREATE TABLE TB_CONFIGURACAO(
COD_CONFIG INT PRIMARY KEY IDENTITY(1,1),
MAX_LIVROS_ALUGADOS INT,
TEMPO_LOCACAO_ALUNO INT,
TEMPO_LOCACAO_FUNCIOARIO INT,
)